### PR TITLE
Remove duplicate imports

### PR DESCRIPTION
**Pull request by soroushj**
Remove imports that import an already-imported package with a different alias. Also, change the import alias of "k8s.io/api/autoscaling/v2" from `v2` to `autoscalingv2` for consistency.

### CODE REVIEW

**Review by mwhittaker — APPROVED** [review]
Nice! Thanks so much for these fixes.

**Comment by mwhittaker** [comment]
Just an update, we're sorting out the permissions issue on #51.

**Comment by spetrovic77** [comment]
Hi @soroushj , can you rebase and the checks will (hopefully) pass?

**Comment by soroushj** [comment]
> Hi @soroushj , can you rebase and the checks will (hopefully) pass?

Hi @spetrovic77, sure, rebased.

**Pull request merged**
